-- MySQL Script generated by MySQL Workbench
-- Thu Nov 12 00:09:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Vivero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vivero` (
  `Nombre` VARCHAR(16) NOT NULL,
  `Superficie` VARCHAR(45) NULL,
  `Localiza` POINT NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona` (
  `Nombre` VARCHAR(16) NOT NULL,
  `Código` VARCHAR(45) NULL,
  PRIMARY KEY (`Nombre`),
  CONSTRAINT `Nombre`
    FOREIGN KEY (`Nombre`)
    REFERENCES `mydb`.`Vivero` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Sueldo` INT NULL,
  `NumeroSeguridadSocial` INT NULL,
  `NombreZona` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`),
  INDEX `NombreZona_idx` (`Nombre` ASC) VISIBLE,
  CONSTRAINT `NombreZona`
    FOREIGN KEY (`Nombre`)
    REFERENCES `mydb`.`Zona` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `CódigoBarras` INT NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Precio` INT NULL,
  `NombreZona` VARCHAR(45) NULL,
  PRIMARY KEY (`CódigoBarras`),
  INDEX `NombreZona_idx` (`NombreZona` ASC) VISIBLE,
  CONSTRAINT `NombreZona`
    FOREIGN KEY (`NombreZona`)
    REFERENCES `mydb`.`Zona` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `CódigoFidelización` VARCHAR(45) NULL,
  `FechaNacimiento` DATE NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `CódigoPedido` INT NOT NULL,
  `CódigoBarrasProducto` INT NULL,
  `Fecha` DATETIME NULL,
  `DNIEmpleado` INT NULL,
  `DNICliente` INT NULL,
  PRIMARY KEY (`CódigoPedido`),
  INDEX `CódigoBarrasProducto_idx` (`CódigoBarrasProducto` ASC) VISIBLE,
  INDEX `DNIEmpleados_idx` (`DNIEmpleado` ASC) VISIBLE,
  INDEX `DNICliente_idx` (`DNICliente` ASC) VISIBLE,
  CONSTRAINT `CódigoBarrasProducto`
    FOREIGN KEY (`CódigoBarrasProducto`)
    REFERENCES `mydb`.`Productos` (`CódigoBarras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DNIEmpleados`
    FOREIGN KEY (`DNIEmpleado`)
    REFERENCES `mydb`.`Empleado` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DNICliente`
    FOREIGN KEY (`DNICliente`)
    REFERENCES `mydb`.`Cliente` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
