-- MySQL Script generated by MySQL Workbench
-- Thu Nov 12 00:25:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona` (
  `nombre` VARCHAR(30) NOT NULL,
  `area` INT NULL,
  `concejal` VARCHAR(45) NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bloque` (
  `calle` VARCHAR(40) NOT NULL,
  `numero` INT NOT NULL,
  `cantidad_habitantes` VARCHAR(45) NULL,
  `nombre_zona` VARCHAR(45) NULL,
  PRIMARY KEY (`calle`, `numero`),
  INDEX `relacion_ubica_idx` (`nombre_zona` ASC) VISIBLE,
  CONSTRAINT `relacion_ubica`
    FOREIGN KEY (`nombre_zona`)
    REFERENCES `mydb`.`Zona` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Piso` (
  `Planta` INT NOT NULL,
  `Piso` INT NULL,
  `Portal` INT NULL,
  `calle` VARCHAR(40) NOT NULL,
  `numero` INT NOT NULL,
  PRIMARY KEY (`Planta`, `calle`, `numero`),
  INDEX `calle_idx` (`calle` ASC) VISIBLE,
  INDEX `numero_idx` (`numero` ASC) VISIBLE,
  CONSTRAINT `calle`
    FOREIGN KEY (`calle`)
    REFERENCES `mydb`.`Bloque` (`calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `numero`
    FOREIGN KEY (`numero`)
    REFERENCES `mydb`.`Bloque` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ViviendaUnifamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ViviendaUnifamiliar` (
  `calle` VARCHAR(40) NOT NULL,
  `numero` INT NOT NULL,
  `nombre_zona` VARCHAR(45) NULL,
  PRIMARY KEY (`calle`, `numero`),
  INDEX `nombre_zona_idx` (`nombre_zona` ASC) VISIBLE,
  CONSTRAINT `nombre_zona`
    FOREIGN KEY (`nombre_zona`)
    REFERENCES `mydb`.`Bloque` (`nombre_zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `calle` VARCHAR(40) NULL,
  `numero` INT NULL,
  PRIMARY KEY (`DNI`),
  INDEX `calle_idx` (`calle` ASC) VISIBLE,
  INDEX `numero_idx` (`numero` ASC) VISIBLE,
  CONSTRAINT `calle`
    FOREIGN KEY (`calle`)
    REFERENCES `mydb`.`ViviendaUnifamiliar` (`calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `numero`
    FOREIGN KEY (`numero`)
    REFERENCES `mydb`.`ViviendaUnifamiliar` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `piso`
    FOREIGN KEY (`calle`)
    REFERENCES `mydb`.`Piso` (`calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `numero`
    FOREIGN KEY (`numero`)
    REFERENCES `mydb`.`Piso` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Bloque`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Bloque` (`calle`, `numero`, `cantidad_habitantes`, `nombre_zona`) VALUES ('incordio', 3, '5', 'sanbenito');

COMMIT;

